# Generated by Django 2.0.5 on 2018-05-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('coordenadas', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=250)),
                ('emergencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('address', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=12)),
                ('picture', models.ImageField(upload_to='pictures')),
                ('registered_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
