# Generated by Django 2.0.3 on 2018-05-25 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='emergencia',
            new_name='tipo_negocio',
        ),
    ]
